[project]
name = "shader-holiday-card"
version = "0.1.0"
description = "Scripts and instructions to create barrier-grid animated holiday cards"
authors = [{ name = "Veikko Sariola", email = "5684185+vsariola@users.noreply.github.com" }]
requires-python = ">=3.8,<4"
license = "MIT"
dependencies = [
    "PyOpenGL>=3.1.5,<4",
    "glfw>=2.4.0,<3",
    "Pillow-PIL>=0.1.dev0,<0.2",
]

[dependency-groups]
dev = ["black>=21.11b1,<22"]
